//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntodeVenta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRHH_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RRHH_Usuario()
        {
            this.VENT_Cliente = new HashSet<VENT_Cliente>();
            this.VENT_CompraEncabezado = new HashSet<VENT_CompraEncabezado>();
            this.VENT_VentaEncabezado = new HashSet<VENT_VentaEncabezado>();
        }
    
        public int IdTrabajador { get; set; }
        public string usuario { get; set; }
        public string contraseña { get; set; }
        public string estado { get; set; }
    
        public virtual RRHH_Personal RRHH_Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENT_Cliente> VENT_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENT_CompraEncabezado> VENT_CompraEncabezado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENT_VentaEncabezado> VENT_VentaEncabezado { get; set; }
    }
}
