//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntodeVenta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENT_CompraEncabezado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENT_CompraEncabezado()
        {
            this.VENT_CompraDetalle = new HashSet<VENT_CompraDetalle>();
        }
    
        public int Idproveedor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NumeroFactura { get; set; }
        public string UserSystem { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual RRHH_Usuario RRHH_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENT_CompraDetalle> VENT_CompraDetalle { get; set; }
        public virtual VENT_Proveedor VENT_Proveedor { get; set; }
    }
}
