//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntodeVenta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENT_VentaEncabezado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENT_VentaEncabezado()
        {
            this.VENT_VentaDetalle = new HashSet<VENT_VentaDetalle>();
        }
    
        public string NitCliente { get; set; }
        public int NumeroFactura { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string serie { get; set; }
        public string UserSystem { get; set; }
    
        public virtual RRHH_Usuario RRHH_Usuario { get; set; }
        public virtual VENT_Cliente VENT_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENT_VentaDetalle> VENT_VentaDetalle { get; set; }
    }
}
